### ISSUE TITLE
Function call to completely wipe the database

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/ssb-db2#198]
Trying to implement a button in ssb-browser-demo to completely wipe the database, indices, and blob store, and force a resync.  However, the method that ssb-browser-core uses for that does not seem to actually work.  See:

https://github.com/arj03/ssb-browser-core/issues/32

Is it possible a function could be added to ssb-db2 to erase everything so we don't have to try to wipe the backing store from outside of it?

**Comment by staltz** [comment]
I think we should recommend to do this outside of ssb-db2. `close()` the ssb instance and rimraf, for instance. That's what we do in Manyverse
