### ISSUE TITLE
onDrain should be called strictly only once

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-db2#235]
In two different occasions I encountered a problem where [onDrain](https://github.com/ssb-ngi-pointer/ssb-db2/blob/82062672503062c4f16d96290c317020addeb163/db.js#L328-L359)'s `cb` is called twice.

Occasion 1: I was trying out the `add-batch` branch with validate2-rsjs, and trying to get the migrate tests to pass, I noticed that the `onDrain` cb was called twice, and this messed up the test results consistently.

Occasion 2: this [crash report in Manyverse](https://gitlab.com/staltz/manyverse/-/issues/1258), about `cb called twice from local api` coming from packet stream and muxrpc, but the blamed code is [actually in Manyverse](https://github.com/staltz/manyverse/blob/b0b793cc20f832fa095f49d2cf31a3f01d4adc5a/src/backend/plugins/aboutSelf.ts#L32-L36) and looks like this:

```js
function get(feedId, cb) {
  ssb.db.onDrain('aboutSelf', () => {
    cb(null, ssb.db.getIndex('aboutSelf').getProfile(feedId));
  });
}
```

Apparently that `cb` is being called twice, which makes it very clear that `ssb.db.onDrain` is calling it twice.

**Comment by staltz** [comment]
Note: it is very possible that this bug was caused by another [bug in async-append-only-log@3.0.8 which was recently fixed](https://github.com/ssb-ngi-pointer/async-append-only-log/pull/33), so let's wait to see if there are more bug reports.

I anyway rolled out a [quick fix for Manyverse](https://github.com/staltz/manyverse/blob/69c2ff3794ea33afe2037cbf2a10976e983c6687/src/backend/plugins/aboutSelf.ts#L33-L35), just because we can't afford crashing user's apps anymore.

**Comment by arj03** [comment]
Was the validate2-rsjs also with async aol 3.0.8 or 3.0.9? That sounds like the easiest way to confirm if the bug is fixed by that or not.

**Comment by staltz** [comment]
I'm gonna gather some courage to say this bug was fixed by https://github.com/ssbc/ssb-db2/pull/337 and close this. :crossed_fingers:
